language: python
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5-dev" # 3.5 development branch
# command to install dependencies
install: 
- "echo '\nconfig interactive false' >> .compmake.rc "
- "pip install -r requirements.txt"
- python setup.py develop
# command to run tests
script: make comptests-run-parallel
addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
    - python-matplotlib
    - python-numpy
    - python-pil