
language: python
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5-dev" # 3.5 development branch
  - "pypy"
# command to install dependencies
cache:
  directories:
    - $HOME/.cache/pip
install: 
- "echo '\nconfig interactive 0' >> .compmake.rc "
- "pip install -r requirements.txt"
- python setup.py develop
# command to run tests
script: 
- make comptests-run-parallel
after_failure:
- comptests out/comptests -c "ls failed"
- comptests out/comptests -c "why failed"
addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
    - python-matplotlib
    - python-numpy
    - python-yaml
    - python-cjson
    - python-pil
    - graphviz # TODO: add check for existence