sudo: required
dist: trusty
language: python
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5-dev" # 3.5 development branch
  # - "pypy"
# command to install dependencies
cache:
  directories:
    - $HOME/.cache/pip
install: 
- "echo '\nconfig interactive 0\nconfig echo_stdout 0\nconfig echo_stderr 0\nconfig echo False\nconfig status_line_enabled False\nconfig console_status False' >> .compmake.rc "
- "cat .compmake.rc"
- "pip install -r requirements.txt"
- dot -V
- "if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install matplotlib ; fi"
- "if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then python -c 'import matplotlib' ; fi"
- "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pypy --version; fi"
- "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pypy -c 'import cffi; print cffi.__version__'; fi"
- "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install git+https://bitbucket.org/pypy/numpy.git; fi"
- python setup.py develop
- "python -c 'import contracts; print contracts.__version__'"
- "python -c 'import quickapp;  print  quickapp.__version__'"
- "python -c 'import compmake;  print  compmake.__version__'"
- "python -c 'import reprep;    print    reprep.__version__'"
# command to run tests
script: 
# run first without contracts
#- make comptests-run-parallel-nocontracts
- QUICKAPP_PROFILE=comptest1.prof make comptests-run-nocontracts
- make -C examples/example-catalogue
- make -C examples/example-battery
# the run with contracts
- make clean comptests-run
after_failure:
- compmake out/comptests -c "ls failed"
- compmake out/comptests -c "why failed"
- cat emergency.dot
addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
    - python-matplotlib
    - python-numpy
    - python-yaml
    - wkhtmltopdf
    - pypy-dev
    - python-cffi  # for pypy/numpy
    # - python-cjson disallowed by Travis!
    # - python-pil not found on Travis
    - graphviz # TODO: add check for existence

notifications:
  slack: censi:0NIaVPIykirj487M6bjKoAAV
