- id: test_flatten
  desc: Flatten
  code:
  - mocdp.dp.Flatten
  - F: 
    - mocdp.posets.PosetProduct
    - subs:
      - - mocdp.posets.PosetProduct
        - subs: [Rcomp_J, Rcomp_g]
      - Rcomp


- id: test_identity
  desc: Identity
  code:
  - mocdp.dp.Identity
  - F: ['mocdp.posets.Rcomp', {}]

- id: test_sum
  desc: Sum
  code:
  - mocdp.dp.Sum
  - F: ['mocdp.posets.Rcomp', {}]

- id: test_split
  desc: Split
  code:
  - mocdp.dp.Split
  - F: ['mocdp.posets.Rcomp', {}]


- id: test_linear
  desc: Testing parallel construction
  code:
  - mocdp.dp.Linear
  - a: 10.0

- id: test_par
  desc: Testing parallel construction
  code:
  - mocdp.dp.Parallel
  - dp1: ['mocdp.dp.Linear', {a: 3.0}]
    dp2: ['mocdp.dp.Linear', {a: 2.0}]


- id: test_linear_J_to_g
  desc: Testing convertions
  code:
  - mocdp.dp.Linear
  - F: Rcomp_J
    R: Rcomp_g
    a: 4.0






