
- id: single
  desc: Single element
  code:
  - mcdp_posets.Single
  - element: "*"

- id: interval01
  desc: Test interval
  code:
  - mcdp_posets.Interval
  - L: 0.0
    U: 1.0

- id: Rcomp
  desc: "[0, ...] U [infinity]"
  code:
  - mcdp_posets.Rcomp
  - {}

- id: Rcomp_g
  desc: grams
  code:
  - mcdp_posets.make_rcompunit
  - units: g

- id: Rcomp_J
  desc: Joules
  code:
  - mcdp_posets.make_rcompunit
  - units: J

- id: U_Rcomp
  desc: upper sets of Rcomp
  code:
  - mcdp_posets.UpperSets
  - P: 'Rcomp'

- id: U_interval01
  desc: upper sets of interval
  code:
  - mcdp_posets.UpperSets
  - P: 'interval01'

- id: square
  desc: "[0,1]x[0,1]"
  code:
  - mcdp_posets.PosetProduct
  - subs: 
    - interval01
    - interval01


- id: R_dimensionless
  desc: dimensionless
  code:
  - mcdp_posets.make_rcompunit
  - units: 'm/m'


- id: Nat
  desc: Natural numbers
  code:
  - mcdp_posets.Nat
  - {}

